global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pixeltracker"
    static_configs:
      - targets: ["pixeltracker-prod:8080", "pixeltracker-enterprise:8080"]
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: /metrics

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb:27017"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch:9200"]
    metrics_path: /_prometheus/metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
