apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixeltracker.fullname" . }}
  labels:
    {{- include "pixeltracker.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pixeltracker.selectorLabels" . | nindent 4 }}
---
{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pixeltracker.configmapName" . }}
  labels:
    {{- include "pixeltracker.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "pixeltracker.environmentConfig" . | nindent 4 }}
{{- end }}
---
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pixeltracker.secretsName" . }}
  labels:
    {{- include "pixeltracker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
